version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=psn_assessment
      - DB_USER=psn
      - DB_PASS=secret
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - "8001:3306"
    volumes:
      - db_dev_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_PASSWORD=secret
      - MYSQL_USER=psn
      - MYSQL_DATABASE=psn_assessment
volumes:
  db_dev_data:
